# See wiki for documentation: https://github.com/realgarit/realbot-g3/tree/main/wiki/pages/Configuration%20-%20OBS.md

obs_websocket:
  host: 127.0.0.1
  port: 4455
  password: password

shiny_delay: 0
discord_delay: 0
screenshot: false
replay_buffer: false
replay_buffer_delay: 0
discord_webhook_url:
